# Generated by Django 4.2.3 on 2023-07-07 08:15

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="current_location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                srid=4326,
            ),
        ),
    ]
