# Generated by Django 4.2.3 on 2023-07-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0005_alter_ride_rider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides_riding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
